name: "devrelease:npm"

on:
  schedule:
    - cron: "10 0 * * *"
  push:
    branches:
      - release-*

jobs:
  publish-canary-npm:
    name: "publish to NPM"
    runs-on: ubuntu-18.04
    if: github.repository == 'microsoft/playwright'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: 'https://registry.npmjs.org'
    - uses: microsoft/playwright-github-action@v1
    - run: npm ci
    - run: npm run build
    - run: node utils/build/update_canary_version.js --today-date
      if: contains(github.ref, 'master')
    - run: node utils/build/update_canary_version.js --commit-timestamp
      if: contains(github.ref, 'release')
    - run: utils/publish_all_packages.sh --tip-of-tree
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

